from typing import Protocol
from .models import EventEnvelope, InstrumentKey, MarketType

class PublicMarketSnapshotAdapter(Protocol):
    async def get_instruments(self, market_type: MarketType, symbol: str | None = None) -> list[EventEnvelope]: ...
    async def get_ticker(self, instrument: InstrumentKey) -> EventEnvelope: ...
    async def get_order_book(self, instrument: InstrumentKey, limit: int = 5) -> EventEnvelope: ...
    async def get_recent_trades(self, instrument: InstrumentKey, limit: int = 100) -> list[EventEnvelope]: ...
    async def get_open_interest(self, instrument: InstrumentKey) -> EventEnvelope: ...
    async def get_current_funding(self, instrument: InstrumentKey) -> EventEnvelope: ...
    async def get_recent_liquidations(self, instrument: InstrumentKey, limit: int = 100) -> list[EventEnvelope]: ...
