"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Moon,MoreHorizontal,Redo2,RefreshCcw,Search,Sun,Undo2,X} from "lucide-react";
import type {DocumentBundle,StudioDocument,StudioObject,WorldOverview} from "@/lib/studio-v5/types";
import {adoptSharedStudio,readLocalStudio} from "@/lib/studio-v5/local-store";
import {isSharedStudio,keepLocalFiles,makeSharedStudio,shouldAdoptRemote,type SharedStudio} from "@/lib/studio-v6/shared-live";
import {driveDisconnect,driveOAuthStart,flushStudioSync,ownerMagicLink,secureStudioAction,studioAction,studioSession,studioSignOut,studioSupabase,studioSyncStatus} from "@/lib/studio-v6/api";
import {STUDIO_DRIVE_ROOT_NAME,STUDIO_DRIVE_ROOT_URL} from "@/lib/studio-v6/drive-scope";
import {NavigatorV6} from "./NavigatorV6";
import {ReactFlowWorldV6} from "./ReactFlowWorldV6";
import {DocumentEditorV6,type DocumentMode} from "./DocumentEditorV6";
import {DocumentLibraryV6,rememberDocument} from "./DocumentLibraryV6";
import {PublicationMenu} from "./PublicationMenu";
import {deepestFrame,snap,titleForKind} from "./world-model";

type Surface="world"|"documents";
type PublishState={url:string;revision:number;publishedAt:string;policy:"LIVE"|"SNAPSHOT"|"MIXED";transport?:"upstream"|"stateless_signed_snapshot"|string};
const PUBLISH_KEY="tqs-studio-v6-publish-state",SURFACE_KEY="tqs-studio-v6-surface",THEME_KEY="tqs-studio-v6-theme";
function dims(kind:string){return kind==="text"?{w:300,h:130}:kind==="task"?{w:310,h:92}:kind==="voice"?{w:330,h:92}:kind==="link"?{w:340,h:108}:kind==="image"?{w:500,h:340}:kind==="video"?{w:500,h:300}:kind==="frame"?{w:1200,h:760}:kind==="chart"?{w:660,h:410}:kind==="diagram"?{w:210,h:78}:kind==="artifact"?{w:1180,h:680}:kind==="deck"?{w:980,h:560}:{w:360,h:120}}
function publicationPolicy(bundle:DocumentBundle|null):"LIVE"|"SNAPSHOT"|"MIXED"{if(!bundle)return"SNAPSHOT";const p=bundle.blocks.map(b=>b.data_spec?.updatePolicy).filter(Boolean) as string[];if(!p.length)return"SNAPSHOT";const live=p.some(x=>x==="LIVE"||x==="MIXED"),snap=p.some(x=>x==="AS_OF"||x==="PUBLICATION_SNAPSHOT"||x==="MIXED");return live&&snap?"MIXED":live?"LIVE":"SNAPSHOT"}
function plainError(error:unknown){const raw=error instanceof Error?error.message:(error&&typeof error==="object"&&"message" in error?String((error as {message?:unknown}).message||""):String(error??""));const text=raw.trim();if(!text||text==="{}"||text==="[object Object]")return"Сервер вернул пустой ответ.";return text}
function lessonHref(documentId:string){return `${location.origin}/studio?document=${encodeURIComponent(documentId)}`}
function readPublish():Record<string,PublishState>{try{return JSON.parse(localStorage.getItem(PUBLISH_KEY)||"{}")||{}}catch{return{}}}
function writePublish(x:Record<string,PublishState>){try{localStorage.setItem(PUBLISH_KEY,JSON.stringify(x))}catch{}}
function sharedHost(){return typeof window!=="undefined"&&(window.location.hostname==="tqs-studio.vercel.app"||/\.vercel\.app$/.test(window.location.hostname))}
async function pullShared(){try{const response=await fetch("/api/studio/live",{cache:"no-store"});if(!response.ok)return null;const body=await response.json();return isSharedStudio(body)?body:null}catch{return null}}
async function pushShared(state:SharedStudio,baseUpdatedAt:string){const response=await fetch("/api/studio/live",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...state,baseUpdatedAt})});if(response.status===409){const current=await response.json().catch(()=>null);throw Object.assign(new Error("SHARED_CONFLICT"),{current:current?.state})}if(!response.ok)throw new Error("SHARED_SAVE_FAILED");const body=await response.json().catch(()=>null);if(!body?.remote)throw new Error("SHARED_REMOTE_DISABLED");const check=await fetch("/api/studio/live",{cache:"no-store"});if(!check.ok)throw new Error("SHARED_READBACK_FAILED");const saved=await check.json();if(saved?.updatedAt!==state.updatedAt)throw new Error("SHARED_READBACK_MISMATCH");return true}
const SHARED_STAMP="tqs-studio-v6-shared-stamp";
function readStamp(){try{return localStorage.getItem(SHARED_STAMP)||""}catch{return""}}
function writeStamp(value:string){try{localStorage.setItem(SHARED_STAMP,value)}catch{}}
function readOperator(){try{return JSON.parse(localStorage.getItem("tqs-studio-v6-operator")||"null")}catch{return null}}

export default function StudioWorldV6(){
 const [overview,setOverview]=useState<WorldOverview|null>(null),[documents,setDocuments]=useState<StudioDocument[]>([]),[bundle,setBundle]=useState<DocumentBundle|null>(null);
 const [surface,setSurfaceState]=useState<Surface>("world"),[docMode,setDocMode]=useState<DocumentMode>("edit"),[docNavOpen,setDocNavOpen]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[focusId,setFocusId]=useState<string|null>(null);
 const [theme,setThemeState]=useState<"dark"|"light">("light"),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[settingsOpen,setSettingsOpen]=useState(false),[statusOpen,setStatusOpen]=useState(false),[driveOpen,setDriveOpen]=useState(false),[publishing,setPublishing]=useState(false),[pdfing,setPdfing]=useState(false),[shareOpen,setShareOpen]=useState(false),[publishMap,setPublishMap]=useState<Record<string,PublishState>>({}),[syncTick,setSyncTick]=useState(0),[sessionUser,setSessionUser]=useState<any>(null),[authOpen,setAuthOpen]=useState(false),[authEmail,setAuthEmail]=useState(""),[authSending,setAuthSending]=useState(false),[sharedStatus,setSharedStatus]=useState<"idle"|"saving"|"saved"|"local">("idle"),[sharedBoot,setSharedBoot]=useState(0),[moreOpen,setMoreOpen]=useState(false),[focusNonce,setFocusNonce]=useState(0);
 const objects=overview?.objects||[],activity=overview?.activity||[];const selectedOne=objects.find(o=>selected.has(o.id))||null;
 const bundleRef=useRef(bundle),sharedReady=useRef(false),pendingPush=useRef(false),heldSync=useRef<string>(""),pushSeq=useRef(0),saveTries=useRef(0);
 bundleRef.current=bundle;
 const setSurface=(v:Surface)=>{setSurfaceState(v);try{localStorage.setItem(SURFACE_KEY,v)}catch{}};const setTheme=(v:"dark"|"light")=>{setThemeState(v);try{localStorage.setItem(THEME_KEY,v)}catch{}};
 const load=useCallback(async()=>{setLoading(true);try{const remote=await pullShared();if(!remote){if(sharedHost()){setSharedStatus("local");setNotice("Общая доска не прочиталась. Локальный черновик не считается записью.");setOverview(null);setLoading(false);return}}else{const local=readLocalStudio();const objects=remote.overview.objects.map(object=>{const prev=local.overview.objects.find(item=>item.id===object.id);return prev?{...object,body:keepLocalFiles(prev.body,object.body)}:object});const blocks=remote.blocks.map(block=>{const prev=local.blocks.find(item=>item.block_id===block.block_id&&item.document_id===block.document_id);return prev?{...block,content:keepLocalFiles(prev.content,block.content)}:block});adoptSharedStudio({overview:{...remote.overview,objects},documents:remote.documents,blocks});writeStamp(remote.updatedAt);setThemeState(remote.theme);const fresh=readLocalStudio();heldSync.current=fresh.overview.world.revision+"|"+fresh.documents.map(item=>item.id+":"+item.revision).join(",");setSharedStatus("saved")}await studioAction("ensureSeed");const [w,d]=await Promise.all([studioAction<WorldOverview>("getWorldOverview"),studioAction<StudioDocument[]>("listDocuments")]);setOverview(w);setDocuments(d);const params=new URLSearchParams(window.location.search),doc=params.get("document");if(doc){const b=await studioAction<DocumentBundle>("getDocument",{documentId:doc});setBundle(b);setSurfaceState("documents")}else{setSurfaceState("world");setSelected(new Set());let saved=false;try{saved=Boolean(JSON.parse(localStorage.getItem("tqs-studio-v6-graphite-viewport")||"null"))}catch{saved=false}if(!saved){const ownerScene=w.objects.find(o=>o.id==="lesson-miro-scene"&&!o.hidden);if(ownerScene){setFocusId(ownerScene.id);setFocusNonce(value=>value+1)}}}setLoading(false);void flushStudioSync().catch(()=>null)}catch(e){setNotice(e instanceof Error?e.message:String(e));setLoading(false)}},[]);
 useEffect(()=>{try{const t=localStorage.getItem(THEME_KEY);if(t==="light"||t==="dark")setThemeState(t);setPublishMap(readPublish())}catch{};void load()},[load]);
 useEffect(()=>{
  let alive=true;
  const adopt=async(remote:SharedStudio)=>{
   const local=readLocalStudio();
   const objects=remote.overview.objects.map(object=>{const prev=local.overview.objects.find(item=>item.id===object.id);return prev?{...object,body:keepLocalFiles(prev.body,object.body)}:object});
   const blocks=remote.blocks.map(block=>{const prev=local.blocks.find(item=>item.block_id===block.block_id&&item.document_id===block.document_id);return prev?{...block,content:keepLocalFiles(prev.content,block.content)}:block});
   adoptSharedStudio({overview:{...remote.overview,objects},documents:remote.documents,blocks});
   const fresh=readLocalStudio();
   heldSync.current=fresh.overview.world.revision+"|"+fresh.documents.map(item=>item.id+":"+item.revision).join(",");
   writeStamp(remote.updatedAt);
   if(!alive)return;
   setOverview(fresh.overview);setDocuments(fresh.documents);setThemeState(remote.theme);
   const open=bundleRef.current?.document.id;
   if(open){const next=await studioAction<DocumentBundle>("getDocument",{documentId:open});if(alive)setBundle(next)}
   setSharedStatus("saved");
  };
  const pull=async()=>{
   const remote=await pullShared();
   if(!alive||!remote||pendingPush.current)return;
   const local=readLocalStudio();
   if(!shouldAdoptRemote({stamp:readStamp(),localRevision:Number(local.overview.world.revision||0),remoteRevision:Number(remote.overview.world.revision||0),remoteUpdatedAt:remote.updatedAt}))return;
   await adopt(remote);
  };
  const boot=async()=>{const remote=await pullShared();if(!alive)return;if(!remote){if(sharedHost())setSharedStatus("local");return}if(!pendingPush.current){const local=readLocalStudio();if(shouldAdoptRemote({stamp:readStamp(),localRevision:Number(local.overview.world.revision||0),remoteRevision:Number(remote.overview.world.revision||0),remoteUpdatedAt:remote.updatedAt}))await adopt(remote)}sharedReady.current=true;setSharedStatus("saved");setSharedBoot(value=>value+1)};
  void boot();
  const id=window.setInterval(()=>void pull(),4000);
  return()=>{alive=false;window.clearInterval(id)};
 },[]);
 useEffect(()=>{
  if(loading||!overview||!sharedReady.current)return;
  const localNow=readLocalStudio();
  const sig=localNow.overview.world.revision+"|"+localNow.documents.map(item=>item.id+":"+item.revision).join(",");
  if(heldSync.current&&heldSync.current===sig)return;
  heldSync.current="";
  pendingPush.current=true;
  const seq=++pushSeq.current;
  const timer=window.setTimeout(()=>{
   const local=readLocalStudio();
   const state=makeSharedStudio({theme,activeDocumentId:bundle?.document.id||null,overview:local.overview,documents:local.documents,blocks:local.blocks,operator:readOperator()});
   setSharedStatus("saving");
   void pushShared(state,readStamp()).then(()=>{if(seq!==pushSeq.current)return;saveTries.current=0;writeStamp(state.updatedAt);setSharedStatus("saved")}).catch((error)=>{if(seq!==pushSeq.current)return;const current=error?.current;if(isSharedStudio(current)){adoptSharedStudio({overview:current.overview,documents:current.documents,blocks:current.blocks});writeStamp(current.updatedAt);heldSync.current=current.overview.world.revision+"|"+current.documents.map((item:StudioDocument)=>item.id+":"+item.revision).join(",");setOverview(current.overview);setDocuments(current.documents);setSharedStatus("saved");return}setSharedStatus("local");if(saveTries.current<3){saveTries.current+=1;window.setTimeout(()=>setSharedBoot(value=>value+1),2500)}}).finally(()=>{if(seq===pushSeq.current)pendingPush.current=false});
  },700);
  return()=>window.clearTimeout(timer);
 },[loading,overview,documents,bundle?.document.id,bundle?.document.revision,theme,sharedBoot]);
 useEffect(()=>{let alive=true;const accept=(session:any)=>{if(!alive)return;setSessionUser(session?.user||null)};void studioSession().then(s=>accept(s)).catch(()=>null);const {data}=studioSupabase().auth.onAuthStateChange((_event,session)=>accept(session));const openAuth=()=>setAuthOpen(true);window.addEventListener("tqs-studio-auth",openAuth);return()=>{alive=false;data.subscription.unsubscribe();window.removeEventListener("tqs-studio-auth",openAuth)}},[]);
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==="1"){e.preventDefault();setSurface("world")}if((e.ctrlKey||e.metaKey)&&e.key==="2"){e.preventDefault();setSurface("documents")}};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)},[]);
 useEffect(()=>{const id=window.setInterval(()=>setSyncTick(v=>v+1),2000);return()=>window.clearInterval(id)},[]);
 const sendOwnerLink=async()=>{const email=authEmail.trim();if(!email||authSending)return;setAuthSending(true);try{const {error}=await ownerMagicLink(email);if(error)throw error;setNotice("Ссылка для входа отправлена. Откройте её на этом устройстве.");setAuthOpen(false)}catch(e){const lesson=bundle?lessonHref(bundle.document.id):"";setNotice(lesson?`Вход не отправлен: ${plainError(e)} Занятие открывается без почты: ${lesson}`:`Вход не отправлен: ${plainError(e)}`)}finally{setAuthSending(false)}};
 const signOut=async()=>{await studioSignOut();setSessionUser(null);setNotice("Вы вышли из сессии Studio. Доска остаётся общей.")};
 const runHistory=async(dir:"undo"|"redo")=>{
  const doc=(window as any).__tqsDocumentHistory;
  if(surface==="documents"&&doc){
   if(dir==="undo"&&doc.canUndo()){doc.undo();return}
   if(dir==="redo"&&doc.canRedo()){doc.redo();return}
  }
  const board=(window as any).__tqsBoardHistory;
  if(dir==="undo"&&board?.canUndo()){board.undo();return}
  if(dir==="redo"&&board?.canRedo()){board.redo();return}
  const run=readLocalStudio().aiRuns?.[0];
  if(!run)return;
  if(dir==="undo"&&run.applied===false)return;
  if(dir==="redo"&&run.applied!==false)return;
  await studioAction(dir==="undo"?"undoAiRun":"redoAiRun",{generationRunId:run.runId,actor:"owner"});
  setOverview(await studioAction<WorldOverview>("getWorldOverview"));
 };
 const setObjects=(fn:(x:StudioObject[])=>StudioObject[])=>setOverview(v=>v?{...v,objects:fn(v.objects)}:v);
 const updateMany=useCallback(async(items:Array<{id:string;patch:any;eventType?:string;summary?:string}>)=>{
  if(!items.length)return;
  const byPatch=new Map(items.map(item=>[item.id,item.patch]));
  setOverview(v=>v?{...v,objects:v.objects.map(o=>byPatch.has(o.id)?{...o,...byPatch.get(o.id),revision:(o.revision||0)+1}:o)}:v);
  const result=await studioAction<any>("updateObjects",{patches:items});
  if(result?.objects){const saved=new Map((result.objects as StudioObject[]).map(o=>[o.id,o]));setOverview(v=>v?{...v,objects:v.objects.map(o=>saved.get(o.id)||o),world:result.worldRevision?{...v.world,revision:result.worldRevision}:v.world}:v)}
 },[]);
 const updateObject=async(id:string,patch:any,eventType?:string,summary?:string)=>{const old=objects.find(o=>o.id===id);if(!old)return;setObjects(v=>v.map(o=>o.id===id?{...o,...patch,revision:(o.revision||0)+1}:o));try{const r=await studioAction<any>("updateObject",{id,revision:old.revision,patch,eventType,summary});if(r?.object)setOverview(v=>v?{...v,objects:v.objects.map(o=>o.id===id?r.object:o),world:r.worldRevision?{...v.world,revision:r.worldRevision}:v.world}:v)}catch(e){setNotice(e instanceof Error?e.message:String(e));throw e}};
 const createObject=async(kind:string,opts:any={})=>{const p=opts.point||{x:900,y:600},parent=deepestFrame(p.x,p.y,objects),id=opts.id||kind+"-"+crypto.randomUUID(),title=opts.title||titleForKind(kind)||kind,d=dims(kind);const relations=opts.relations||[...(parent?[{type:"contains",targetId:parent.id}]:[]),...(opts.annotates?[{type:"annotates",targetId:opts.annotates}]:[])];const topZ=objects.reduce((m,o)=>Math.max(m,o.z||0),10);const row:any={id,world_key:overview?.world.world_key||"tqs-studio-world",kind,semantic_path:opts.semantic_path||(parent?parent.semantic_path+"/"+title:title),parent_id:opts.parent_id===undefined?(parent?.id||null):opts.parent_id,x:snap(p.x),y:snap(p.y),w:opts.w||d.w,h:opts.h||d.h,z:opts.z||(kind==="frame"?2:topZ+1),title,body:opts.body??(kind==="frame"?{workspaceCard:true}:{}),relations,status:opts.status??(kind==="task"?"NEW":kind==="voice"?"WAITING_RECORDING":null),hidden:false};const res=await studioAction<any>("createWorldObject",{object:row});const out=res?.object||row;setOverview(v=>v?{...v,objects:[...v.objects.filter(o=>o.id!==out.id),out],world:res?.worldRevision?{...v.world,revision:res.worldRevision}:v.world}:v);setSelected(new Set([out.id]));return out as StudioObject};
 const restore=async(snapshot:StudioObject[])=>{const now=new Map(objects.map(o=>[o.id,o])),wanted=new Map(snapshot.map(o=>[o.id,o]));for(const [id,o] of now)if(!wanted.has(id)&&!o.hidden)await updateObject(id,{hidden:true},"undo","Undo: объект скрыт");for(const o of snapshot){const cur=now.get(o.id);if(cur){const patch={x:o.x,y:o.y,w:o.w,h:o.h,z:o.z,title:o.title,body:o.body,relations:o.relations,status:o.status,hidden:o.hidden,parent_id:o.parent_id,semantic_path:o.semantic_path};const before={x:cur.x,y:cur.y,w:cur.w,h:cur.h,z:cur.z,title:cur.title,body:cur.body,relations:cur.relations,status:cur.status,hidden:cur.hidden,parent_id:cur.parent_id,semantic_path:cur.semantic_path};if(JSON.stringify(before)!==JSON.stringify(patch))await updateObject(o.id,patch,"undo","Undo/redo")}else await createObject(o.kind,{...o,point:{x:o.x,y:o.y}})}const w=await studioAction<WorldOverview>("getWorldOverview");setOverview(w)};
 const focus=(id:string)=>{setSurface("world");setFocusId(id);setFocusNonce(value=>value+1);setSelected(new Set([id]));history.replaceState(null,"","/studio")};
 const openDocument=async(id:string)=>{const b=await studioAction<DocumentBundle>("getDocument",{documentId:id});setBundle(b);setSurface("documents");setDocMode("edit");setDocNavOpen(false);rememberDocument(id);history.replaceState(null,"",`/studio?document=${encodeURIComponent(id)}`)};
 const refreshDocument=async(id?:string)=>{const doc=id||bundle?.document.id;if(!doc)return;const b=await studioAction<DocumentBundle>("getDocument",{documentId:doc});setBundle(b);setDocuments(await studioAction("listDocuments"));setSyncTick(v=>v+1)};
 const createDocument=async(explicitId?:string)=>{const source=objects.find(o=>o.id===(explicitId||selectedOne?.id));if(!source)return;const b=await studioAction<DocumentBundle>("createDocument",{title:"Документ — "+source.title,semanticPath:source.semantic_path,frameId:source.kind==="frame"?source.id:source.parent_id,kind:source.semantic_path.startsWith("Статьи")?"article":"instruction"});await refreshDocument(b.document.id);setSurface("documents")};
 const publish=async()=>{if(!bundle||publishing)return;setPublishing(true);try{await refreshDocument(bundle.document.id);const fresh=await studioAction<DocumentBundle>("getDocument",{documentId:bundle.document.id});const x=await studioAction<any>("createShare",{documentId:fresh.document.id,appOrigin:window.location.origin,bundle:fresh});const check=await fetch(x.url,{cache:"no-store"});if(!check.ok)throw new Error(`Публикация не открылась (${check.status}).`);const state:PublishState={url:x.url,revision:fresh.document.revision,publishedAt:new Date().toISOString(),policy:publicationPolicy(fresh),transport:x.transport||"upstream"},next={...readPublish(),[fresh.document.id]:state};writePublish(next);setPublishMap(next);setBundle(fresh);setShareOpen(true);setNotice("Опубликовано и проверено")}catch(e){setNotice(`Публикация не подтверждена: ${plainError(e)} Занятие открывается по ссылке ${lessonHref(bundle.document.id)}`)}finally{setPublishing(false)}};
 const disablePublication=async()=>{if(!bundle||publishing)return;setPublishing(true);try{if(pub?.transport==="stateless_signed_snapshot"){const next={...readPublish()};delete next[bundle.document.id];writePublish(next);setPublishMap(next);setNotice("Резервная ссылка убрана из Studio; ранее выданный снимок остаётся доступен");return}await studioAction("disableShare",{documentId:bundle.document.id,shareUrl:pub?.url});const next={...readPublish()};delete next[bundle.document.id];writePublish(next);setPublishMap(next);setNotice("Публичная ссылка отключена")}catch(e){setNotice("Не удалось отключить ссылку: "+plainError(e))}finally{setPublishing(false)}};
 const copyLessonLink=async()=>{if(!bundle)return;const url=lessonHref(bundle.document.id);try{await navigator.clipboard.writeText(url);setNotice("Ссылка на занятие скопирована")}catch{setNotice(url)}};
 const copyPublication=async()=>{if(!bundle)return;const url=pub?.url||lessonHref(bundle.document.id);try{await navigator.clipboard.writeText(url);setNotice(pub?.url?"Ссылка публикации скопирована":"Ссылка на занятие скопирована")}catch{setNotice(url)}};
 const createPdf=async()=>{if(!bundle||pdfing)return;setPdfing(true);try{const q=new URLSearchParams({documentId:bundle.document.id});if(pub?.url)q.set("share",pub.url);const r=await fetch(`/api/studio/pdf?${q.toString()}`,{cache:"no-store"});if(!r.ok)throw new Error(`PDF_${r.status}`);const blob=await r.blob();if(blob.size<12000)throw new Error("PDF_TOO_SMALL");const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=(bundle.document.title||"TQS Studio").replace(/[\\/:*?"<>|]+/g," ").trim()+".pdf";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("PDF создан")}catch(e){setNotice("PDF не создан: "+(e instanceof Error?e.message:String(e)))}finally{setPdfing(false)}};
 const pub=bundle?publishMap[bundle.document.id]:undefined,pubStatus=!bundle?null:!pub?"DRAFT":pub.revision===bundle.document.revision?"PUBLISHED":"STALE";const sync=studioSyncStatus();void syncTick;
 return <main className="v6-shell" data-visual="graphite" data-theme={theme} data-surface={surface} data-testid="tqs-studio-v6">
  <header className="v6-topbar" data-studio-ui><div className="v6-brand"><strong>TQS</strong></div><div className="v6-mode" role="tablist" aria-label="Режим"><button type="button" role="tab" aria-selected={surface==="world"} className={surface==="world"?"is-on":""} onClick={()=>{setSurface("world");history.replaceState(null,"","/studio")}}>Мир</button><button type="button" role="tab" aria-selected={surface==="documents"} className={surface==="documents"?"is-on":""} onClick={()=>{setSurface("documents");setDocNavOpen(true);if(!bundle)history.replaceState(null,"","/studio?surface=documents")}}>Документы</button></div><nav className="v6-crumbs" aria-label="Раздел"><b>TQS Studio</b></nav><div className="v6-top-actions"><button type="button" aria-label="Поиск" title="Поиск" onClick={()=>window.dispatchEvent(new Event("tqs-studio-search"))}><Search size={15}/></button><button type="button" className={"v6-save-chip"+(sharedStatus==="saved"?" is-saved":sharedStatus==="local"?" is-warn":"")} data-testid="studio-shared-status" aria-label="Состояние сохранения" onClick={()=>setStatusOpen(value=>!value)}>{sharedStatus==="saving"?"Сохраняю…":sharedStatus==="saved"?"Сохранено":sharedStatus==="local"?"Нет связи":"Сверяю"}</button>{sync.pending>0&&<span className="v6-sync is-pending" data-testid="studio-sync">{sync.flushing?"Синхронизация":"Не отправлено · "+sync.pending}</span>}<button aria-label="Отменить" title="Отменить" onClick={()=>void runHistory("undo")}><Undo2 size={14}/></button><button aria-label="Повторить" title="Повторить" onClick={()=>void runHistory("redo")}><Redo2 size={14}/></button><button type="button" aria-label={theme==="dark"?"Светлая тема":"Тёмная тема"} title={theme==="dark"?"Светлая тема":"Тёмная тема"} onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun size={15}/>:<Moon size={15}/>}</button><button aria-label="Ещё" title="Ещё" onClick={()=>setMoreOpen(value=>!value)}><MoreHorizontal size={15}/></button>{statusOpen&&<div className="v6-status-popover" data-testid="studio-status-popover"><strong>{sharedStatus==="saving"?"Сохраняю":sharedStatus==="local"?"Синхронизация не прошла":"Сохранено"}</strong><span>{savedClock(readStamp())?`Последняя запись: ${savedClock(readStamp())}`:"Запись ещё не отмечена"}</span><span>{sync.pending>0?"Есть правки, которые ещё не записались.":"Сверка с общей доской в порядке."}</span><button type="button" onClick={()=>{setSettingsOpen(true);setStatusOpen(false)}}>Подробнее в настройках</button></div>}{moreOpen&&<div className="v6-more-menu"><button onClick={()=>{setTheme(theme==="dark"?"light":"dark");setMoreOpen(false)}}>{theme==="dark"?"Светлая тема":"Тёмная тема"}</button><button onClick={()=>{setSettingsOpen(true);setMoreOpen(false)}}>Настройки</button>{sessionUser?.email?<button onClick={()=>{setMoreOpen(false);void signOut()}}>{sessionUser.email}</button>:<button onClick={()=>{setAuthOpen(true);setMoreOpen(false)}}>Войти</button>}</div>}</div></header>
  {notice&&<button className="v6-notice" data-studio-ui onClick={()=>setNotice("")}>{notice}<X size={12}/></button>}
  {authOpen&&<div className="v6-auth-backdrop" data-studio-ui onMouseDown={e=>{if(e.target===e.currentTarget)setAuthOpen(false)}}><section className="v6-auth-card"><header><div><strong>Общий TQS Studio</strong><small>Одна доска для вас и ChatGPT</small></div><button aria-label="Закрыть вход" onClick={()=>setAuthOpen(false)}><X size={15}/></button></header><p>Войдите по e-mail. Пароль не нужен: Supabase пришлёт одноразовую ссылку, после которой эта доска будет работать как owner-сессия.</p><label><span>E-mail</span><input type="email" value={authEmail} autoFocus placeholder="you@example.com" onChange={e=>setAuthEmail(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void sendOwnerLink()}}/></label><button className="primary" disabled={!authEmail.trim()||authSending} onClick={()=>void sendOwnerLink()}>{authSending?"Отправка…":"Получить ссылку для входа"}</button><small>Google Drive остаётся резервной копией/экспортом. Рабочие данные Studio хранятся в Supabase.</small></section></div>}
  <NavigatorV6 objects={objects} documents={documents} activity={activity} selectedId={selectedOne?.id||null} surface={surface} onWorld={()=>{setSurface("world");history.replaceState(null,"","/studio")}} onDocuments={()=>{setSurface("documents");setDocNavOpen(true);if(!bundle)history.replaceState(null,"","/studio?surface=documents")}} onFocus={focus} onOpenDocument={id=>void openDocument(id)} onSettings={()=>setSettingsOpen(true)} onCreate={kind=>window.dispatchEvent(new CustomEvent("tqs-studio-create",{detail:kind}))} onTool={tool=>window.dispatchEvent(new CustomEvent("tqs-studio-tool",{detail:tool}))}/>
  {surface==="world"?<div className="v6-world-shell"><div className="v6-world-main">{loading||!overview?<div className="v6-loading">{loading?"Загрузка TQS Studio…":"Общая доска не прочиталась. Обновите страницу — локальная копия не открывается вместо неё."}</div>:<ReactFlowWorldV6 objects={objects} selected={selected} setSelected={setSelected} focusId={focusId} focusNonce={focusNonce} onObjectsLocal={setObjects} onPatch={updateObject} onCommit={updateMany} onCreate={createObject} onOpenDocument={id=>void openDocument(id)} onAssemble={id=>void createDocument(id)} onRestore={restore} notice={setNotice}/>}</div></div>:
   <div className={"v6-doc-shell"+(docMode==="preview"?" is-preview":" is-edit")} data-mode={docMode}><DocumentLibraryV6 documents={documents} activeId={bundle?.document.id||null} statusFor={id=>{const published=publishMap[id];const doc=documents.find(item=>item.id===id);if(!published||!doc)return "DRAFT";return published.revision===doc.revision?"PUBLISHED":"STALE"}} open={docNavOpen} onOpenChange={setDocNavOpen} onOpen={id=>void openDocument(id)}/><section className="v6-doc-main">{bundle?<><header className="v6-doc-toolbar" data-studio-ui><div className="v6-doc-title"><small>{docMode==="edit"?"Редактирование":"Просмотр"}</small><h1>{bundle.document.title}</h1><span>{bundle.document.semantic_path}</span></div><div className="v6-doc-modes" role="tablist" aria-label="Режим документа" data-testid="document-mode"><button role="tab" aria-selected={docMode==="edit"} className={docMode==="edit"?"active":""} onClick={()=>setDocMode("edit")}>Статья</button><button role="tab" aria-selected={docMode==="preview"} className={docMode==="preview"?"active":""} onClick={()=>setDocMode("preview")}>Занятие</button></div><div className="v6-doc-actions"><button type="button" onClick={()=>bundle.document.frame_id&&focus(bundle.document.frame_id)}>На доске</button><button type="button" data-testid="copy-document-link" onClick={()=>void copyLessonLink()}>Ссылка</button><PublicationMenu open={shareOpen} status={pubStatus} url={pub?.url||lessonHref(bundle.document.id)} publishing={publishing} pdfing={pdfing} onToggle={()=>setShareOpen(v=>!v)} onPublish={()=>void publish()} onCopy={()=>void copyPublication()} onOpen={()=>window.open(pub?.url||lessonHref(bundle.document.id),"_blank","noopener,noreferrer")} onPdf={()=>void createPdf()} onDisable={()=>void disablePublication()}/></div></header><DocumentEditorV6 bundle={bundle} mode={docMode==="edit"?"edit":"preview"} onBundle={b=>{setBundle(b);setDocuments(v=>v.map(d=>d.id===b.document.id?b.document:d));setSyncTick(x=>x+1)}}/></>:<div className="v6-doc-empty">Выберите документ в библиотеке</div>}</section></div>}
  {driveOpen&&<DrivePanelV6 onClose={()=>setDriveOpen(false)} notice={setNotice}/>}
  {settingsOpen&&<SettingsPanel theme={theme} setTheme={setTheme} status={sharedStatus} savedAt={readStamp()} onClose={()=>setSettingsOpen(false)} onReload={()=>void load()} onDrive={()=>{setSettingsOpen(false);setDriveOpen(true)}} notice={setNotice}/>}
 </main>
}
function savedClock(value:string){const time=new Date(value);return Number.isNaN(time.getTime())?"":time.toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}
function SettingsPanel({theme,setTheme,status,savedAt,onClose,onReload,onDrive,notice}:{theme:"dark"|"light";setTheme:(value:"dark"|"light")=>void;status:"idle"|"saving"|"saved"|"local";savedAt:string;onClose:()=>void;onReload:()=>void;onDrive:()=>void;notice:(value:string)=>void}){
 const when=savedClock(savedAt);
 const [advanced,setAdvanced]=useState(false),[confirmReset,setConfirmReset]=useState(false),[drive,setDrive]=useState<{connected:boolean;email:string;sync:string}|null>(null);
 useEffect(()=>{let stop=false;void studioAction<any>("driveStatus").then(value=>{if(stop)return;const connection=value?.connection;setDrive({connected:connection?.status==="CONNECTED",email:String(connection?.connected_email||""),sync:String(connection?.last_sync_at||"")})}).catch(()=>{if(!stop)setDrive({connected:false,email:"",sync:""})});return()=>{stop=true}},[]);
 const setProfile=(profile:"trackpad"|"mouse")=>{localStorage.setItem("tqs-studio-v6-rf-input-profile",profile);window.dispatchEvent(new CustomEvent("tqs-studio-input-profile",{detail:profile}));notice(profile==="trackpad"?"Трекпад: два пальца двигают доску":"Мышь: колесо меняет масштаб")};
 return <aside className="v6-settings" data-studio-ui data-testid="studio-settings"><header><strong>Настройки</strong><button aria-label="Закрыть настройки" onClick={onClose}><X size={15}/></button></header>
  <section className="v6-settings-card"><b>Google Drive</b>{drive?.connected?<><span>{drive.email||"Подключён"}</span><span>Корень: {STUDIO_DRIVE_ROOT_NAME}</span><span>Последняя сверка: {drive.sync?savedClock(drive.sync)||drive.sync:"—"}</span></>:<span>Не подключён</span>}<button type="button" onClick={onDrive}>{drive?.connected?"Открыть":"Подключить"}</button></section>
  <section><b>Тема</b><div><button type="button" className={theme==="light"?"is-on":""} onClick={()=>setTheme("light")}>Светлая</button><button type="button" className={theme==="dark"?"is-on":""} onClick={()=>setTheme("dark")}>Тёмная</button></div></section>
  <section><b>Ввод</b><span>Жест не меняет комнату, в которой вы работаете.</span><div><button type="button" onClick={()=>setProfile("trackpad")}>Трекпад</button><button type="button" onClick={()=>setProfile("mouse")}>Мышь</button></div></section>
  <section><b>Синхронизация</b><span>{status==="saved"?"Последняя запись на месте.":status==="saving"?"Запись идёт.":status==="local"?"Последняя запись не дошла.":when?"Общая доска открыта.":"Открываю доску."}</span>{when&&<span>Последняя запись: {when}</span>}<div><button type="button" onClick={onReload}><RefreshCcw size={13}/>Перечитать</button></div></section>
  <section><button type="button" onClick={()=>setAdvanced(value=>!value)}>{advanced?"Скрыть дополнительное":"Дополнительно"}</button>{advanced&&<div className="v6-settings-advanced">{confirmReset?<><span>Перечитать доску с сайта? Локальные несохранённые правки этого браузера могут смениться общей версией.</span><button type="button" onClick={()=>{setConfirmReset(false);onReload()}}>Перечитать</button><button type="button" onClick={()=>setConfirmReset(false)}>Отмена</button></>:<button type="button" onClick={()=>setConfirmReset(true)}>Перечитать сохранённую доску</button>}</div>}</section>
 </aside>
}

type DriveState={connection?:{status?:string;connected_email?:string;last_sync_at?:string;last_error?:string;metadata?:any};conflicts?:any[];oauthConfigured?:boolean;redirectUri?:string;scopes?:string[]};
function DrivePanelV6({onClose,notice}:{onClose:()=>void;notice:(v:string)=>void}){
 const [state,setState]=useState<DriveState|null>(null),[files,setFiles]=useState<any[]>([]),[busy,setBusy]=useState(false),[signedIn,setSignedIn]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const session=await studioSession();setSignedIn(Boolean(session));const s=await studioAction<DriveState>("driveStatus");setState(s);if(session&&s.connection?.status==="CONNECTED"){const x=await secureStudioAction<any[]>("driveListRoot");setFiles(Array.isArray(x)?x:[])}}catch(e){setError(plainError(e))}finally{setBusy(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const connect=async()=>{if(!signedIn){setError("Сначала войдите в Studio. Документы уже сохраняются без диска.");window.dispatchEvent(new Event("tqs-studio-auth"));return}setBusy(true);try{const x=await driveOAuthStart(window.location.href);window.location.assign(x.url)}catch(e:any){setError(plainError(e)||"Диск не подключён. Studio продолжает хранить занятие у себя.");if(e?.details?.redirectUri)setState(v=>({...v,oauthConfigured:false}))}finally{setBusy(false)}};
 const sync=async()=>{setBusy(true);try{const x=await secureStudioAction<any>("driveSyncCheckpoint");if(x?.conflict)throw new Error("DRIVE_CONFLICT");notice("Корень прочитан, запись проверена");await load()}catch(e){setError(e instanceof Error?e.message:String(e));setBusy(false)}};
 const disconnect=async()=>{setBusy(true);try{await driveDisconnect();notice("Google Drive отключён");await load()}catch(e){setError(e instanceof Error?e.message:String(e));setBusy(false)}};
 const c=state?.connection;
 const connected=c?.status==="CONNECTED";
 const status=c?.last_error?"Ошибка":connected&&c?.last_sync_at?"Синхронизировано":"Ожидание";
 return <aside className="v6-drive-panel" data-studio-ui data-testid="v6-drive-panel"><header><div><strong>Google Drive</strong><small>{connected?"Подключён":"Не подключён"}</small></div><button aria-label="Закрыть диск" onClick={onClose}><X size={15}/></button></header>
  <section className="v6-drive-status"><span className={"drive-dot "+(connected?"ok":"")}/><div><b>{status}</b><small>{c?.connected_email||"аккаунт не подключён"}</small></div></section>
  <section><span>Корень: {STUDIO_DRIVE_ROOT_NAME}</span><span>Последняя сверка: {c?.last_sync_at||"—"}</span></section>
  {!signedIn&&<section><p>Сначала войдите в Studio, затем нажмите «Подключить».</p></section>}
  {signedIn&&state&&!state.oauthConfigured&&<section><p>Подключение Google ещё не настроено на сайте.</p></section>}
  <section className="v6-drive-actions"><button onClick={()=>void connect()} disabled={busy}>{connected?"Переподключить":"Подключить"}</button><button onClick={()=>window.open(STUDIO_DRIVE_ROOT_URL,"_blank","noopener,noreferrer")}>Открыть корень</button><button onClick={()=>void sync()} disabled={busy||!connected}>Синхронизировать</button><button onClick={()=>void disconnect()} disabled={busy||!connected}>Отключить</button></section>
  {error&&<section className="v6-drive-error">{error}</section>}
  <section><b>Файлы корня</b>{files.length?files.map(f=><div className="v6-drive-file" key={f.id}><span>{f.name}</span><small>{f.modifiedTime||"—"}</small></div>):<p>Список появится после подключения.</p>}</section>
 </aside>
}
