"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {BookOpen,Copy,FileText,Image as ImageIcon,Link as LinkIcon,Maximize2,Mic,Move,PenLine,Plus,SquarePen,Trash2} from "lucide-react";
import type {DataSpec,StudioObject} from "@/lib/studio-v5/types";
import {StudioMarketChart} from "@/components/studio-v5/MarketChart";
import {studioAction} from "@/lib/studio-v6/api";
import {RichEditor} from "./RichEditor";
import {Camera,InputProfile,Point,ToolMode,classifyUrl,clampZoom,deepestFrame,descendants,escapeHtml,isEditableTarget,looksLikeMouseWheel,pointInObject,snap,zoomAt} from "./world-model";

const WORLD_W=14000,WORLD_H=9000,PROFILE_KEY="tqs-studio-v6-input-profile";
type Ctx={kind:"blank"|"object"|"multi";sx:number;sy:number;world:Point;id?:string};
type Gesture={type:"pan";button:number;sx:number;sy:number;x:number;y:number;right:boolean;moved:boolean;hitId?:string}|{type:"move";id:string;sx:number;sy:number;start:Map<string,{x:number;y:number}>}|{type:"resize";id:string;dir:string;sx:number;sy:number;start:{x:number;y:number;w:number;h:number}}|{type:"marquee";start:Point;current:Point}|null;
type Props={objects:StudioObject[];selected:Set<string>;setSelected:(ids:Set<string>)=>void;focusId?:string|null;onObjectsLocal:(fn:(x:StudioObject[])=>StudioObject[])=>void;onPatch:(id:string,patch:any,eventType?:string,summary?:string)=>Promise<void>;onCreate:(kind:string,opts?:any)=>Promise<StudioObject>;onOpenDocument:(id:string)=>void;onRestore:(snapshot:StudioObject[])=>Promise<void>;notice:(s:string)=>void};

export function WorldCanvasV6({objects,selected,setSelected,focusId,onObjectsLocal,onPatch,onCreate,onOpenDocument,onRestore,notice}:Props){
 const canvas=useRef<HTMLElement|null>(null),gestureRef=useRef<Gesture>(null),lastPointer=useRef<Point&{at:number}>({x:800,y:500,at:0}),drawImage=useRef<string|null>(null),undo=useRef<StudioObject[][]>([]),redo=useRef<StudioObject[][]>([]),space=useRef(false);
 const [camera,setCamera]=useState<Camera>({x:40,y:30,zoom:.55}),[profile,setProfileState]=useState<InputProfile>("auto"),[tool,setTool]=useState<ToolMode>("select"),[gesture,setGesture]=useState<Gesture>(null),[context,setContext]=useState<Ctx|null>(null),[drawPoints,setDrawPoints]=useState<Point[]>([]),[editing,setEditing]=useState<string|null>(null),[grid,setGrid]=useState(false),[deviceOpen,setDeviceOpen]=useState(false);
 const setProfile=(p:InputProfile)=>{setProfileState(p);try{localStorage.setItem(PROFILE_KEY,p)}catch{}};
 const beginGesture=(g:Gesture)=>{gestureRef.current=g;setGesture(g)};
 useEffect(()=>{try{const p=localStorage.getItem(PROFILE_KEY) as InputProfile|null;if(p&&["auto","mouse","trackpad"].includes(p))setProfileState(p)}catch{}},[]);
 const selectedObjects=useMemo(()=>objects.filter(o=>selected.has(o.id)),[objects,selected]);const lod=camera.zoom<.22?"far":camera.zoom<.52?"mid":"near";
 const remember=useCallback(()=>{undo.current.push(structuredClone(objects));if(undo.current.length>60)undo.current.shift();redo.current=[]},[objects]);
 const doUndo=useCallback(async()=>{const x=undo.current.pop();if(!x)return;redo.current.push(structuredClone(objects));await onRestore(x);setContext(null)},[objects,onRestore]);
 const doRedo=useCallback(async()=>{const x=redo.current.pop();if(!x)return;undo.current.push(structuredClone(objects));await onRestore(x);setContext(null)},[objects,onRestore]);
 const screenToWorld=useCallback((cx:number,cy:number)=>{const r=canvas.current?.getBoundingClientRect();if(!r)return{x:0,y:0};return{x:(cx-r.left-camera.x)/camera.zoom,y:(cy-r.top-camera.y)/camera.zoom}},[camera]);
 const insertionPoint=()=>{if(Date.now()-lastPointer.current.at<30000)return{x:lastPointer.current.x,y:lastPointer.current.y};const r=canvas.current?.getBoundingClientRect();return r?screenToWorld(r.left+r.width/2,r.top+r.height/2):{x:900,y:600}};
 useEffect(()=>{if(!focusId||!canvas.current)return;const o=objects.find(x=>x.id===focusId);if(!o)return;const r=canvas.current.getBoundingClientRect(),z=clampZoom(Math.min(1.2,Math.max(.24,Math.min((r.width-140)/Math.max(1,o.w),(r.height-140)/Math.max(1,o.h)))));setCamera({zoom:z,x:r.width/2-(o.x+o.w/2)*z,y:r.height/2-(o.y+o.h/2)*z});},[focusId,objects]);
 const fitWorld=()=>{const roots=objects.filter(o=>o.kind==="frame"&&!o.parent_id&&!o.hidden),el=canvas.current;if(!roots.length||!el)return;const minX=Math.min(...roots.map(o=>o.x)),minY=Math.min(...roots.map(o=>o.y)),maxX=Math.max(...roots.map(o=>o.x+o.w)),maxY=Math.max(...roots.map(o=>o.y+o.h)),r=el.getBoundingClientRect(),z=clampZoom(Math.min((r.width-100)/(maxX-minX),(r.height-100)/(maxY-minY),1));setCamera({zoom:z,x:50-minX*z,y:50-minY*z})};
 useEffect(()=>{const el=canvas.current;if(!el)return;const wheel=(e:WheelEvent)=>{if(isEditableTarget(e.target))return;e.preventDefault();const r=el.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top;if(e.shiftKey&&!e.ctrlKey){setCamera(c=>({...c,x:c.x-(e.deltaY+e.deltaX)}));return}const useProfile=profile==="auto"?(e.ctrlKey?"trackpad":looksLikeMouseWheel(e)?"mouse":"trackpad"):profile;if(useProfile==="mouse"){const delta=e.deltaY||e.deltaX;setCamera(c=>zoomAt(c,sx,sy,Math.exp(-delta*.0024)));return}if(e.ctrlKey){setCamera(c=>zoomAt(c,sx,sy,Math.exp(-e.deltaY*.006)));return}setCamera(c=>({...c,x:c.x-e.deltaX,y:c.y-e.deltaY}))};el.addEventListener("wheel",wheel,{passive:false});return()=>el.removeEventListener("wheel",wheel)},[profile]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(isEditableTarget(e.target))return;const mod=e.ctrlKey||e.metaKey;if(e.code==="Space"){space.current=true;e.preventDefault()}if(e.key==="Escape"){setTool("select");setEditing(null);setContext(null);setDrawPoints([])}if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();void(e.shiftKey?doRedo():doUndo())}if(mod&&e.key.toLowerCase()==="y"){e.preventDefault();void doRedo()}if(mod&&e.key.toLowerCase()==="c"&&selected.size){e.preventDefault();void copySelection()}};const up=(e:KeyboardEvent)=>{if(e.code==="Space")space.current=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[selected,doUndo,doRedo]);
 const copySelection=async()=>{const rows=selectedObjects.map(o=>({...o}));try{await navigator.clipboard.writeText("TQS-STUDIO-OBJECTS:"+JSON.stringify(rows));notice(`${rows.length} объект(ов) скопировано`)}catch{}};
 const duplicateRows=async(rows:StudioObject[],point?:Point)=>{if(!rows.length)return;remember();const minX=Math.min(...rows.map(o=>o.x)),minY=Math.min(...rows.map(o=>o.y)),p=point||insertionPoint(),created:string[]=[];for(const o of rows){const id=o.kind+"-"+crypto.randomUUID();const obj=await onCreate(o.kind,{id,title:o.title,point:{x:p.x+(o.x-minX)+24,y:p.y+(o.y-minY)+24},w:o.w,h:o.h,body:structuredClone(o.body),status:o.status,relations:structuredClone(o.relations||[])});created.push(obj.id)}setSelected(new Set(created))};
 const classifyText=async(text:string,point?:Point)=>{const t=text.trim();if(!t)return;if(t.startsWith("TQS-STUDIO-OBJECTS:")){try{await duplicateRows(JSON.parse(t.slice(19)),point);return}catch{}}const target=point||insertionPoint(),u=classifyUrl(t);if(u){remember();if(u.kind==="video")await onCreate("video",{point:target,title:u.provider==="youtube"?"YouTube":u.provider==="rutube"?"RuTube":"Vimeo",body:{url:u.url,embedUrl:u.embed,provider:u.provider}});else if(u.kind==="image")await onCreate("image",{point:target,title:"Изображение",body:{url:u.url,provider:"url"}});else if(u.kind==="file")await onCreate("file",{point:target,title:u.filename,body:{url:u.url,filename:u.filename,mimeType:"application/pdf"}});else await onCreate("link",{point:target,title:u.host||"Ссылка",body:{url:u.url,host:u.host}});return}remember();await onCreate("text",{point:target,title:"Текст",body:{html:`<p>${escapeHtml(t)}</p>`}})};
 const handleFiles=async(files:File[],point?:Point)=>{remember();const target=point||insertionPoint();for(const file of files.slice(0,8)){const dataUrl=await fileToDataUrl(file),asset=await studioAction<any>("attachAsset",{dataUrl,filename:file.name}),kind=file.type.startsWith("image/")?"image":file.type.startsWith("video/")?"video":"file";await onCreate(kind,{point:target,title:file.name,body:{assetId:asset.asset.id,previewUrl:asset.signedUrl||dataUrl,mimeType:file.type,filename:file.name}})}};
 const onPaste=async(e:React.ClipboardEvent)=>{if(isEditableTarget(e.target))return;const files=Array.from(e.clipboardData.files);if(files.length){e.preventDefault();await handleFiles(files);return}const internal=e.clipboardData.getData("application/x-tqs-studio")||e.clipboardData.getData("text/plain");if(internal){e.preventDefault();await classifyText(internal)}};
 const onDrop=async(e:React.DragEvent)=>{e.preventDefault();const p=screenToWorld(e.clientX,e.clientY),files=Array.from(e.dataTransfer.files);if(files.length){await handleFiles(files,p);return}const text=e.dataTransfer.getData("text/uri-list")||e.dataTransfer.getData("text/plain");if(text)await classifyText(text,p)};
 const beginMove=(e:React.PointerEvent,o:StudioObject)=>{if(e.button!==0||tool!=="select"||isEditableTarget(e.target))return;e.stopPropagation();e.preventDefault();remember();const ids=selected.has(o.id)&&selected.size>1?new Set(selected):new Set([o.id]);if(o.kind==="frame")for(const id of descendants(o.id,objects))ids.add(id);for(const a of objects.filter(x=>x.relations?.some((r:any)=>r.type==="annotates"&&r.targetId===o.id)))ids.add(a.id);const start=new Map<string,{x:number;y:number}>();for(const id of ids){const x=objects.find(z=>z.id===id);if(x)start.set(id,{x:x.x,y:x.y})}beginGesture({type:"move",id:o.id,sx:e.clientX,sy:e.clientY,start})};
 const beginResize=(e:React.PointerEvent,o:StudioObject,dir:string)=>{if(e.button!==0)return;e.stopPropagation();e.preventDefault();remember();beginGesture({type:"resize",id:o.id,dir,sx:e.clientX,sy:e.clientY,start:{x:o.x,y:o.y,w:o.w,h:o.h}})};
 const persistGesture=async(g:Exclude<Gesture,null>)=>{if(g.type==="move"){for(const id of g.start.keys()){const cur=objects.find(o=>o.id===id),old=g.start.get(id);if(!cur||!old||(cur.x===old.x&&cur.y===old.y))continue;let patch:any={x:cur.x,y:cur.y};if(id===g.id){const parent=deepestFrame(cur.x+cur.w/2,cur.y+cur.h/2,objects,cur.id);if(parent?.id!==cur.parent_id){const oldPrefix=cur.semantic_path,newPath=parent?parent.semantic_path+"/"+cur.title:cur.title;patch={...patch,parent_id:parent?.id||null,semantic_path:newPath,relations:[...(cur.relations||[]).filter((r:any)=>r.type!=="contains"),...(parent?[{type:"contains",targetId:parent.id}]:[])]};if(cur.kind==="frame"){const ds=descendants(cur.id,objects);onObjectsLocal(v=>v.map(x=>ds.has(x.id)?{...x,semantic_path:x.semantic_path.startsWith(oldPrefix)?newPath+x.semantic_path.slice(oldPrefix.length):x.semantic_path}:x))}}}await onPatch(id,patch,id===g.id?"semantic_move":undefined,id===g.id?"Объект перемещён":undefined)}}else if(g.type==="resize"){const cur=objects.find(o=>o.id===g.id);if(cur)await onPatch(cur.id,{x:cur.x,y:cur.y,w:cur.w,h:cur.h},"resize","Размер объекта изменён")}};
 const pointerMove=(e:React.PointerEvent)=>{const p=screenToWorld(e.clientX,e.clientY);lastPointer.current={...p,at:Date.now()};const g=gestureRef.current;if(g?.type==="pan"){const dx=e.clientX-g.sx,dy=e.clientY-g.sy;if(g.right&&Math.hypot(dx,dy)>5){g.moved=true;setContext(null)}setCamera(c=>({...c,x:g.x+dx,y:g.y+dy}));return}if(g?.type==="move"){const dx=(e.clientX-g.sx)/camera.zoom,dy=(e.clientY-g.sy)/camera.zoom;onObjectsLocal(v=>v.map(o=>{const s=g.start.get(o.id);return s?{...o,x:snap(s.x+dx),y:snap(s.y+dy)}:o}));return}if(g?.type==="resize"){const dx=(e.clientX-g.sx)/camera.zoom,dy=(e.clientY-g.sy)/camera.zoom,s=g.start;let{x,y,w,h}=s;if(g.dir.includes("e"))w=Math.max(120,s.w+dx);if(g.dir.includes("s"))h=Math.max(64,s.h+dy);if(g.dir.includes("w")){x=Math.min(s.x+s.w-120,s.x+dx);w=s.w+(s.x-x)}if(g.dir.includes("n")){y=Math.min(s.y+s.h-64,s.y+dy);h=s.h+(s.y-y)}onObjectsLocal(v=>v.map(o=>o.id===g.id?{...o,x:snap(x),y:snap(y),w:snap(w),h:snap(h)}:o));return}if(g?.type==="marquee"){beginGesture({...g,current:p});return}if(tool!=="select"&&drawPoints.length)setDrawPoints(v=>[...v,p])};
 const finishPointer=async(e?:React.PointerEvent)=>{const g=gestureRef.current;if(g?.type==="pan"&&g.right){beginGesture(null);if(!g.moved&&e){const r=e.currentTarget.getBoundingClientRect(),p=screenToWorld(e.clientX,e.clientY);openContext(e.clientX-r.left,e.clientY-r.top,p,g.hitId)}else setContext(null);return}beginGesture(null);if(tool!=="select"&&drawPoints.length>1){const pts=drawPoints;setDrawPoints([]);const minX=Math.min(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxX=Math.max(...pts.map(p=>p.x)),maxY=Math.max(...pts.map(p=>p.y)),mid=pts[Math.floor(pts.length/2)],image=(drawImage.current?objects.find(o=>o.id===drawImage.current):null)||objects.filter(o=>o.kind==="image"&&pointInObject(mid,o)).at(-1);remember();await onCreate("annotation",{point:{x:minX,y:minY},w:Math.max(10,maxX-minX),h:Math.max(10,maxY-minY),title:tool==="marker"?"Маркер":tool==="arrow"?"Стрелка":"Карандаш",body:{annotationKind:tool==="pen"?"pencil":tool,points:pts.map(p=>({x:p.x-minX,y:p.y-minY}))},annotates:image?.id});drawImage.current=null}if(g?.type==="marquee"){const a=g.start,b=g.current,minX=Math.min(a.x,b.x),maxX=Math.max(a.x,b.x),minY=Math.min(a.y,b.y),maxY=Math.max(a.y,b.y);setSelected(new Set(objects.filter(o=>!o.hidden&&o.x+o.w>=minX&&o.x<=maxX&&o.y+o.h>=minY&&o.y<=maxY).map(o=>o.id)));return}if(g&&g.type!=="pan")await persistGesture(g)};
 const openContext=(sx:number,sy:number,p:Point,id?:string)=>{if(id){const ids=selected.has(id)?selected:new Set([id]);setSelected(ids);setContext({kind:ids.size>1?"multi":"object",sx,sy,world:p,id})}else{setSelected(new Set());setContext({kind:"blank",sx,sy,world:p})}};
 const onCanvasDown=(e:React.PointerEvent)=>{if((e.target as HTMLElement).closest?.("[data-studio-ui]"))return;const p=screenToWorld(e.clientX,e.clientY);lastPointer.current={...p,at:Date.now()};setContext(null);(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);if(e.button===2){e.preventDefault();const hit=(e.target as HTMLElement).closest?.("[data-studio-object]") as HTMLElement|null;beginGesture({type:"pan",button:2,sx:e.clientX,sy:e.clientY,x:camera.x,y:camera.y,right:true,moved:false,hitId:hit?.dataset.studioId});return}if(e.button===1||(space.current&&e.button===0)){e.preventDefault();beginGesture({type:"pan",button:e.button,sx:e.clientX,sy:e.clientY,x:camera.x,y:camera.y,right:false,moved:false});return}if(e.button!==0)return;if(tool!=="select"){const hit=(e.target as HTMLElement).closest?.("[data-studio-object]") as HTMLElement|null;drawImage.current=hit?.dataset.studioKind==="image"?(hit.dataset.studioId||null):null;setDrawPoints([p]);return}if(e.target===e.currentTarget){setEditing(null);beginGesture({type:"marquee",start:p,current:p});if(!e.shiftKey)setSelected(new Set())}};
 const selectObject=(e:React.PointerEvent,o:StudioObject)=>{if(e.button!==0||tool!=="select")return;e.stopPropagation();if(e.shiftKey){const n=new Set(selected);n.has(o.id)?n.delete(o.id):n.add(o.id);setSelected(n)}else if(!selected.has(o.id)||selected.size!==1)setSelected(new Set([o.id]))};
 const hideSelected=async()=>{remember();for(const o of selectedObjects)await onPatch(o.id,{hidden:true},"hide","Объект скрыт");setSelected(new Set());setContext(null)};
 const alignSelected=async(axis:"left"|"top")=>{if(selectedObjects.length<2)return;remember();const value=axis==="left"?Math.min(...selectedObjects.map(o=>o.x)):Math.min(...selectedObjects.map(o=>o.y));for(const o of selectedObjects)await onPatch(o.id,axis==="left"?{x:value}:{y:value},"align","Выравнивание");setContext(null)};
 const groupSelected=async()=>{if(selectedObjects.length<2)return;remember();const pad=80,minX=Math.min(...selectedObjects.map(o=>o.x))-pad,minY=Math.min(...selectedObjects.map(o=>o.y))-pad,maxX=Math.max(...selectedObjects.map(o=>o.x+o.w))+pad,maxY=Math.max(...selectedObjects.map(o=>o.y+o.h))+pad,frame=await onCreate("frame",{point:{x:minX,y:minY},w:maxX-minX,h:maxY-minY,title:"Группа"});for(const o of selectedObjects)await onPatch(o.id,{parent_id:frame.id,semantic_path:frame.semantic_path+"/"+o.title,relations:[...(o.relations||[]).filter((r:any)=>r.type!=="contains"),{type:"contains",targetId:frame.id}]},"group","Объект добавлен в группу");setSelected(new Set([frame.id]));setContext(null)};
 const addFromContext=async(kind:string,extra:any={})=>{if(!context)return;remember();await onCreate(kind,{point:context.world,...extra});setContext(null)};
 return <section ref={canvas as any} className={["v6-canvas",grid?"has-grid":""].join(" ")} data-testid="world-canvas-v6" tabIndex={0} onPaste={onPaste} onDrop={e=>void onDrop(e)} onDragOver={e=>e.preventDefault()} onPointerDown={onCanvasDown} onPointerMove={pointerMove} onPointerUp={e=>void finishPointer(e)} onPointerCancel={e=>void finishPointer(e)} onContextMenu={e=>{e.preventDefault()}}>
  <div className="v6-world" data-lod={lod} style={{width:WORLD_W,height:WORLD_H,transform:`translate(${camera.x}px,${camera.y}px) scale(${camera.zoom})`}}>
   {objects.filter(o=>!o.hidden&&o.kind!=="annotation").sort((a,b)=>a.z-b.z).map(o=><WorldObject key={o.id} object={o} lod={lod} childCount={objects.filter(x=>!x.hidden&&x.parent_id===o.id).length} compact={lod==="far"&&o.kind!=="frame"&&!selected.has(o.id)} selected={selected.has(o.id)} single={selected.size===1} editing={editing===o.id} onSelect={e=>selectObject(e,o)} onMove={e=>beginMove(e,o)} onResize={(e,d)=>beginResize(e,o,d)} onEdit={()=>setEditing(o.id)} onStop={()=>setEditing(null)} onPatch={(p,t,s)=>onPatch(o.id,p,t,s)} onOpenDocument={onOpenDocument}/>)}
   {objects.filter(o=>!o.hidden&&o.kind==="annotation").map(o=><Annotation key={o.id} object={o}/>)}
   {drawPoints.length>1&&<svg className="v6-draw-draft" width={WORLD_W} height={WORLD_H}><polyline points={drawPoints.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="#d7ad55" strokeWidth={tool==="marker"?18:3} strokeLinecap="round"/></svg>}
   {gesture?.type==="marquee"&&<div className="v6-marquee" style={{left:Math.min(gesture.start.x,gesture.current.x),top:Math.min(gesture.start.y,gesture.current.y),width:Math.abs(gesture.start.x-gesture.current.x),height:Math.abs(gesture.start.y-gesture.current.y)}}/>}
  </div>
  <div className="v6-tools" data-studio-ui><button className={tool==="select"?"active":""} title="Выбор · V" onClick={()=>setTool("select")}><Move size={14}/></button><button className={tool==="pen"?"active":""} title="Карандаш · P" onClick={()=>setTool(tool==="pen"?"select":"pen")}><PenLine size={14}/></button><button className={tool==="marker"?"active":""} title="Маркер" onClick={()=>setTool(tool==="marker"?"select":"marker")}><SquarePen size={14}/></button><button className={tool==="arrow"?"active":""} title="Стрелка" onClick={()=>setTool(tool==="arrow"?"select":"arrow")}>↗</button><button title="Добавить" onClick={()=>{const p=insertionPoint();setContext({kind:"blank",sx:70,sy:55,world:p})}}><Plus size={14}/></button><button title="Вписать мир" onClick={fitWorld}><Maximize2 size={14}/></button></div>
  <div className="v6-input-profile" data-studio-ui data-testid="input-profile"><span>{Math.round(camera.zoom*100)}%</span><button aria-label="Устройство ввода" title="Устройство ввода" onClick={()=>setDeviceOpen(v=>!v)}>⌁</button>{deviceOpen&&<div className="v6-device-popover"><strong>Устройство ввода</strong>{(["auto","mouse","trackpad"] as InputProfile[]).map(p=><button key={p} className={profile===p?"active":""} onClick={()=>{setProfile(p);setDeviceOpen(false)}}>{p==="auto"?"Авто":p==="mouse"?"Mouse":"Trackpad"}</button>)}</div>}</div>
  {context&&<ContextMenu context={context} selected={selectedObjects} onAdd={addFromContext} onDuplicate={()=>void duplicateRows(selectedObjects,{x:context.world.x,y:context.world.y})} onHide={()=>void hideSelected()} onGroup={()=>void groupSelected()} onAlign={a=>void alignSelected(a)} onClose={()=>setContext(null)} onDraw={m=>{setTool(m);setContext(null)}}/>}
 </section>
}
function WorldObject({object:o,lod,childCount,compact,selected,single,editing,onSelect,onMove,onResize,onEdit,onStop,onPatch,onOpenDocument}:{object:StudioObject;lod:"far"|"mid"|"near";childCount:number;compact:boolean;selected:boolean;single:boolean;editing:boolean;onSelect:(e:React.PointerEvent)=>void;onMove:(e:React.PointerEvent)=>void;onResize:(e:React.PointerEvent,d:string)=>void;onEdit:()=>void;onStop:()=>void;onPatch:(p:any,t?:string,s?:string)=>Promise<void>;onOpenDocument:(id:string)=>void}){
 if(compact)return <button data-studio-object data-studio-id={o.id} data-studio-kind={o.kind} data-testid={`lod-chip-${o.kind}`} className="v6-lod-chip" style={{left:o.x,top:o.y,zIndex:o.z}} onPointerDown={e=>{onSelect(e);onMove(e)}}><span>{iconFor(o.kind)}</span><b>{o.title}</b></button>;
 return <div data-studio-object data-studio-id={o.id} data-studio-kind={o.kind} data-testid={`world-${o.kind}`} className={["v6-object","kind-"+o.kind,selected?"is-selected":"",o.kind==="text"?"content-first":""].join(" ")} style={{left:o.x,top:o.y,width:o.w,height:o.h,zIndex:o.z}} onPointerDown={onSelect} onDoubleClick={o.kind==="text"?onEdit:undefined}>
  {o.kind==="frame"?<div className={"v6-frame-head lod-"+lod} onPointerDown={onMove}><strong>{o.id==="frame-learning"?"ACADEMY · ОБУЧЕНИЕ":o.title}</strong><small>{childCount?childCount+" материалов":""}</small></div>:<div className="v6-object-handle" onPointerDown={onMove}><span>{o.title}</span><span>⋯</span></div>}
  {o.kind!=="frame"&&<div className="v6-object-content">{o.kind==="text"&&<TextObject object={o} editing={editing} onEdit={onEdit} onStop={onStop} onPatch={onPatch}/>} {o.kind==="task"&&<TaskObject object={o} onPatch={onPatch}/>} {o.kind==="voice"&&<VoiceObject object={o} onPatch={onPatch}/>} {(o.kind==="image"||o.kind==="video"||o.kind==="file")&&<AssetObject object={o}/>} {o.kind==="link"&&<LinkObject object={o}/>} {o.kind==="chart"&&<StudioMarketChart dataSpec={o.body?.dataSpec as DataSpec}/>} {o.kind==="documentRef"&&<button className="v6-doc-ref" onClick={()=>onOpenDocument(o.body?.documentId||o.relations?.find((r:any)=>r.type==="document_of")?.targetId)}><BookOpen size={18}/>Открыть документ</button>}</div>}
  {selected&&single&&(["nw","n","ne","e","se","s","sw","w"] as const).map(d=><span key={d} className={`v6-resize v6-resize-${d}`} data-studio-ui onPointerDown={e=>onResize(e,d)}/>)}
 </div>
}
function TextObject({object:o,editing,onEdit,onStop,onPatch}:{object:StudioObject;editing:boolean;onEdit:()=>void;onStop:()=>void;onPatch:(p:any,t?:string,s?:string)=>Promise<void>}){const html=typeof o.body?.html==="string"?o.body.html:"<p></p>";return <div className="v6-text" onDoubleClick={onEdit}>{editing?<RichEditor html={html} autofocus onBlur={h=>{void onPatch({body:{...o.body,html:h}},"text_update","Текст обновлён");onStop()}}/>:<div className="v6-text-read" dangerouslySetInnerHTML={{__html:html}}/>}</div>}
function TaskObject({object:o,onPatch}:{object:StudioObject;onPatch:(p:any,t?:string,s?:string)=>Promise<void>}){const [v,setV]=useState(o.body?.title||o.title);return <div className="v6-task"><button aria-label="Статус задачи" onClick={()=>void onPatch({status:o.status==="DONE"?"NEW":"DONE",body:{...o.body,done:o.status!=="DONE"}},"task","Статус задачи изменён")}>{o.status==="DONE"?"✓":"○"}</button><input value={v} onChange={e=>setV(e.target.value)} onBlur={()=>{if(v!==(o.body?.title||o.title))void onPatch({title:v,body:{...o.body,title:v}},"task","Задача обновлена")}}/></div>}
function VoiceObject({object:o,onPatch}:{object:StudioObject;onPatch:(p:any,t?:string,s?:string)=>Promise<void>}){const rec=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);const [recording,setRecording]=useState(false),[url,setUrl]=useState(o.body?.previewUrl||"");useEffect(()=>{if(!url&&o.body?.assetId)void studioAction<any>("getAssetUrl",{assetId:o.body.assetId}).then(x=>setUrl(x.signedUrl||""))},[url,o.body?.assetId]);const start=async()=>{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType||"audio/webm"});stream.getTracks().forEach(t=>t.stop());void fileToDataUrl(new File([blob],`voice-${Date.now()}.webm`,{type:blob.type})).then(dataUrl=>studioAction<any>("attachAsset",{dataUrl,filename:`voice-${Date.now()}.webm`})).then(a=>{setUrl(a.signedUrl||"");return onPatch({body:{...o.body,assetId:a.asset.id,previewUrl:a.signedUrl||"",status:"Ожидает расшифровки"},status:"WAITING_TRANSCRIPTION"},"voice","Голосовая заметка сохранена")})};r.start();rec.current=r;setRecording(true)};return <div className="v6-voice">{recording?<button onClick={()=>{rec.current?.stop();setRecording(false)}}>Стоп</button>:<button onClick={()=>void start()}><Mic size={13}/>Записать</button>}{url&&<audio controls src={url}/>}<small>{o.body?.status||"Готово к записи"}</small></div>}
function AssetObject({object:o}:{object:StudioObject}){const [url,setUrl]=useState(o.body?.previewUrl||o.body?.url||"");useEffect(()=>{if(!url&&o.body?.assetId)void studioAction<any>("getAssetUrl",{assetId:o.body.assetId}).then(x=>setUrl(x.signedUrl||""))},[url,o.body?.assetId]);if(o.kind==="image")return <div className="v6-asset">{url?<img src={url} alt={o.title}/>:<ImageIcon size={28}/>}</div>;if(o.kind==="video")return <div className="v6-asset">{o.body?.embedUrl?<iframe src={o.body.embedUrl} title={o.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:url?<video src={url} controls/>:<span>Видео</span>}</div>;return <a className="v6-file" href={url||o.body?.url||"#"} target="_blank" rel="noreferrer"><FileText size={18}/><span>{o.body?.filename||o.title}</span><small>{o.body?.mimeType||"document"}</small></a>}
function LinkObject({object:o}:{object:StudioObject}){let host=o.body?.host||"";try{host=host||new URL(o.body?.url||"").hostname}catch{}return <a className="v6-link" href={o.body?.url||"#"} target="_blank" rel="noreferrer"><LinkIcon size={16}/><div><strong>{o.title||host||"Ссылка"}</strong><small>{host}</small><span>{o.body?.url}</span></div></a>}
function Annotation({object:o}:{object:StudioObject}){const p=o.body?.points||[],kind=o.body?.annotationKind;return <svg className="v6-annotation" data-testid="world-annotation" style={{left:o.x,top:o.y,width:o.w,height:o.h,zIndex:o.z}} viewBox={`0 0 ${Math.max(1,o.w)} ${Math.max(1,o.h)}`}><defs><marker id={`arrow-${o.id}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="#d7ad55"/></marker></defs><polyline points={p.map((x:any)=>`${x.x},${x.y}`).join(" ")} fill="none" stroke={kind==="marker"?"rgba(215,173,85,.42)":"#d7ad55"} strokeWidth={kind==="marker"?18:3} strokeLinecap="round" strokeLinejoin="round" markerEnd={kind==="arrow"?`url(#arrow-${o.id})`:undefined}/></svg>}
function ContextMenu({context,selected,onAdd,onDuplicate,onHide,onGroup,onAlign,onClose,onDraw}:{context:Ctx;selected:StudioObject[];onAdd:(k:string,e?:any)=>Promise<void>;onDuplicate:()=>void;onHide:()=>void;onGroup:()=>void;onAlign:(a:"left"|"top")=>void;onClose:()=>void;onDraw:(m:ToolMode)=>void}){if(context.kind==="blank")return <div className="v6-context v6-context-add" style={{left:context.sx,top:context.sy}} data-studio-ui data-testid="context-blank"><strong>Добавить сюда</strong><button onClick={()=>void onAdd("text")}>Текст</button><button onClick={()=>void onAdd("task")}>Задача</button><button onClick={()=>void onAdd("voice")}>Голосовая заметка</button><details><summary>Медиа</summary><button onClick={()=>void onAdd("image")}>Изображение / скриншот</button><button onClick={()=>void onAdd("video")}>Видео</button><button onClick={()=>void onAdd("file")}>PDF / документ</button><button onClick={()=>void onAdd("link")}>Ссылка</button></details><button onClick={()=>void onAdd("chart",{body:{dataSpec:{provider:"MOEX_ISS",instrument:{family:"SI",resolver:"front_active_contract"},metric:"ohlcv_session",relativeRange:{tradingSessions:2},fixedRange:null,transforms:["group_by_session","cumulative_volume"],display:{renderer:"studio_market_chart"},updatePolicy:"LIVE",asOf:null}}})}>График / данные</button><details><summary>Структура и рисунок</summary><button onClick={()=>void onAdd("frame")}>Фрейм / раздел</button><button onClick={()=>onDraw("pen")}>Карандаш</button><button onClick={()=>onDraw("marker")}>Маркер</button><button onClick={()=>onDraw("arrow")}>Стрелка</button></details><button onClick={onClose}>Закрыть</button></div>;
 if(context.kind==="multi")return <div className="v6-context" style={{left:context.sx,top:context.sy}} data-studio-ui data-testid="context-multi"><strong>{selected.length} объектов</strong><button onClick={onGroup}>Сгруппировать</button><button onClick={()=>onAlign("left")}>Выровнять по левому краю</button><button onClick={()=>onAlign("top")}>Выровнять по верхнему краю</button><button onClick={onDuplicate}><Copy size={13}/>Дублировать</button><button className="danger" onClick={onHide}><Trash2 size={13}/>Скрыть</button><button onClick={onClose}>Закрыть</button></div>;
 const o=selected[0];return <div className="v6-context" style={{left:context.sx,top:context.sy}} data-studio-ui data-testid="context-object"><strong>{o?.title||"Объект"}</strong><button onClick={onDuplicate}><Copy size={13}/>Дублировать</button>{o?.kind==="frame"&&<button onClick={()=>void onAdd("text")}>Добавить текст рядом</button>}<button className="danger" onClick={onHide}><Trash2 size={13}/>Скрыть объект</button><button onClick={onClose}>Закрыть</button></div>}
function iconFor(k:string){return k==="text"?"T":k==="task"?"✓":k==="voice"?"◉":k==="image"?"▧":k==="video"?"▶":k==="link"?"↗":k==="chart"?"⌁":k==="documentRef"?"D":"•"}
function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
