"use client";
import * as React from "react";
import Link from "next/link";
type A=any;
const labels:Record<string,string>={price_move:"Движение цены",price_move_extreme:"Экстремальное движение",turnover:"Оборот",turnover_extreme:"Экстремальный оборот",open_interest:"Open Interest",funding:"Funding",moex_turnover_tod:"Всплеск оборота",moex_volume_tod:"Всплеск объёма",moex_trade_intensity:"Интенсивность сделок",moex_price_impulse:"Ценовой импульс",moex_absorption:"Поглощение",moex_expansion:"Расширение"};
export function AnomalyExplorer(){
 const [all,setAll]=React.useState<A[]>([]); const [moex,setMoex]=React.useState<A[]>([]); const [filter,setFilter]=React.useState("all");
 React.useEffect(()=>{Promise.all([fetch("/api/tqs/anomalies?limit=250&min_score=50").then(r=>r.json()),fetch("/api/tqs/moex").then(r=>r.json())]).then(([a,m])=>{setAll(Array.isArray(a)?a:[]);setMoex(m?.rows??[])})},[]);
 const rows=React.useMemo(()=>[...moex.map(x=>({...x,score:x.attention_score,provider:"moex"})),...all].filter(x=>filter==="all"||(x.signals??[]).includes(filter)).sort((a,b)=>(b.score??0)-(a.score??0)).slice(0,150),[all,moex,filter]);
 const signals=Array.from(new Set([...moex,...all].flatMap((x:any)=>x.signals??[]))).slice(0,18);
 return <div className="space-y-3"><div><h1 className="lab-type-display text-xl">Аномалии</h1><p className="text-xs text-lab-dim">Что необычного происходит сейчас · клик по инструменту открывает исследование</p></div>
 <div className="flex flex-wrap gap-1"><button onClick={()=>setFilter("all")} className={`rounded-md border px-2 py-1 text-[10px] ${filter==="all"?"border-lab-cyan text-lab-cyan":"border-lab-border text-lab-dim"}`}>Все</button>{signals.map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-md border px-2 py-1 text-[10px] ${filter===s?"border-lab-cyan text-lab-cyan":"border-lab-border text-lab-dim"}`}>{labels[s]??s}</button>)}</div>
 <div className="overflow-hidden rounded-xl border border-lab-border/50"><div className="grid grid-cols-[80px_1fr_90px_90px] bg-lab-surface-1/70 px-3 py-2 text-[9px] uppercase tracking-wider text-lab-dim"><span>Score</span><span>Инструмент / причина</span><span>Рынок</span><span>Цена</span></div>{rows.map((x:any)=>{const symbol=x.symbol??x.quote?.symbol??x.canonical_id; const href=x.provider==="moex"&&symbol&&!String(symbol).match(/[0-9]/)?`/stocks/${symbol}`:null; return <div key={x.canonical_id} className="grid grid-cols-[80px_1fr_90px_90px] items-start border-t border-lab-border/20 px-3 py-2 text-xs"><span className="font-mono text-lab-cyan">{Math.round(x.score??0)}</span><div>{href?<Link className="font-mono font-semibold text-lab-text hover:text-lab-cyan" href={href}>{symbol}</Link>:<span className="font-mono font-semibold">{symbol}</span>}<div className="mt-1 flex flex-wrap gap-1">{(x.signals??[]).map((s:string)=><span key={s} className="rounded bg-lab-surface-2 px-1.5 py-0.5 text-[9px] text-lab-muted">{labels[s]??s}</span>)}</div></div><span className="text-lab-muted">{x.provider}</span><span className="font-mono">{x.price??x.quote?.last??"—"}</span></div>})}</div></div>
}
