"use client";
import * as React from "react";
import Link from "next/link";
const pct=(v:any)=>v==null?"—":`${v>=0?"+":""}${Number(v).toFixed(2)}%`;
const dt=(ms:any)=>ms?new Date(ms).toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";
export function EpisodeResearch(){
 const [episodes,setEpisodes]=React.useState<any[]>([]),[findings,setFindings]=React.useState<any[]>([]),[sel,setSel]=React.useState<any>(null),[detail,setDetail]=React.useState<any>(null);
 React.useEffect(()=>{Promise.all([fetch("/api/tqs/episodes?limit=200").then(r=>r.json()),fetch("/api/tqs/findings").then(r=>r.json())]).then(([e,f])=>{setEpisodes(Array.isArray(e)?e:[]);setFindings(Array.isArray(f)?f:[])})},[]);
 const open=(e:any)=>{setSel(e);setDetail(null);fetch(`/api/tqs/episodes/${e.id}`).then(r=>r.json()).then(setDetail)};
 return <div className="space-y-3"><div className="flex items-end justify-between"><div><h1 className="lab-type-display text-xl">Исследования аномалий</h1><p className="text-xs text-lab-dim">Эпизод → исход → похожие случаи → статистическая гипотеза</p></div><div className="text-[10px] text-lab-dim">{episodes.length} эпизодов · {findings.length} паттернов</div></div>
 <div className="grid gap-3 xl:grid-cols-[1.1fr_.9fr]"><div className="overflow-hidden rounded-xl border border-lab-border/50"><div className="grid grid-cols-[80px_110px_1fr_70px] bg-lab-surface-1/70 px-3 py-2 text-[9px] uppercase text-lab-dim"><span>Score</span><span>Время</span><span>Инструмент / сигналы</span><span>Статус</span></div>{episodes.slice(0,80).map(e=><button key={e.id} onClick={()=>open(e)} className="grid w-full grid-cols-[80px_110px_1fr_70px] border-t border-lab-border/20 px-3 py-2 text-left text-xs hover:bg-lab-cyan/5"><span className="font-mono text-lab-cyan">{Math.round(e.peak_score)}</span><span className="text-lab-dim">{dt(e.opened_at_ms)}</span><span><b className="font-mono">{e.symbol}</b><span className="ml-2 text-[9px] text-lab-muted">{(e.signals??[]).join(" · ")}</span></span><span className={e.status==="active"?"text-emerald-300":"text-lab-dim"}>{e.status}</span></button>)}</div>
 <div className="space-y-3">{sel?<><div className="rounded-xl border border-lab-border/50 bg-lab-surface-1/40 p-4"><div className="flex justify-between"><div><div className="font-mono text-xl">{sel.symbol}</div><div className="text-[10px] text-lab-dim">{sel.pattern_key}</div></div><span className="font-mono text-lab-cyan">{Math.round(sel.peak_score)}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs">{Object.entries(detail?.outcome?.returns_pct??{}).map(([k,v])=><div key={k} className="rounded-lg border border-lab-border/30 p-2"><div className="font-mono">{pct(v)}</div><div className="text-[9px] text-lab-dim">{k}</div></div>)}</div><div className="mt-3 text-xs text-lab-muted">Похожих исторических случаев: <b className="text-lab-text">{detail?.similar?.length??"…"}</b></div></div><div className="rounded-xl border border-lab-border/50 bg-lab-surface-1/30 p-3"><div className="mb-2 text-[10px] uppercase text-lab-muted">Похожие случаи</div>{(detail?.similar??[]).slice(0,8).map((x:any)=><div key={x.episode.id} className="grid grid-cols-[1fr_70px_70px] border-t border-lab-border/20 py-2 text-xs"><span>{x.episode.symbol} · {dt(x.episode.opened_at_ms)}</span><span className="font-mono">{pct(x.outcome?.returns_pct?.["1h"])}</span><span className="font-mono">{pct(x.outcome?.returns_pct?.["4h"])}</span></div>)}</div></>:<div className="grid min-h-[280px] place-items-center rounded-xl border border-dashed border-lab-border text-xs text-lab-dim">Выберите эпизод слева</div>}</div></div>
 <div className="rounded-xl border border-lab-border/50 bg-lab-surface-1/30 p-3"><div className="mb-3 text-[10px] uppercase tracking-wider text-lab-muted">Накопленные статистические паттерны</div><div className="grid gap-2 lg:grid-cols-2">{findings.slice(0,20).map((f:any)=><div key={f.pattern_key} className="rounded-lg border border-lab-border/30 p-3"><div className="text-[10px] text-lab-muted">{f.pattern_key}</div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><span>n=<b>{f.sample_count}</b></span><span>1ч <b className="font-mono">{pct(f.median_forward_1h_pct)}</b></span><span>4ч <b className="font-mono">{pct(f.median_forward_4h_pct)}</b></span></div><div className="mt-2 text-[10px] text-lab-dim">Продолжение: 1ч {Math.round((f.continuation_rate_1h??0)*100)}% · 4ч {Math.round((f.continuation_rate_4h??0)*100)}% · {f.status}</div></div>)}</div></div></div>
}
