import assert from "node:assert/strict";
import { explainAnomaly, qualityFromTimestamp } from "../lib/domain/preparation-market";
import { moexTradingStatus } from "../lib/domain/moex-trading-status";

const anomaly = explainAnomaly({ change1dPct: 4.2, volatility: 1.2, relativeTurnover: 2.4, rollRatio: .42, dte: 5 });
assert.equal(anomaly.severity, "extreme");
assert.ok(anomaly.reasons.some((reason) => reason.includes("σ")));
assert.ok(anomaly.reasons.some((reason) => reason.includes("оборот")));
assert.equal(qualityFromTimestamp(new Date().toISOString(), true), "LIVE");
assert.equal(qualityFromTimestamp(new Date(Date.now() - 40 * 60_000).toISOString(), true), "STALE");
assert.equal(qualityFromTimestamp(new Date().toISOString(), false), "CLOSED");
assert.equal(moexTradingStatus("T"), "regular");
assert.equal(moexTradingStatus("O"), "opening");
assert.equal(moexTradingStatus("C"), "closed");
assert.equal(moexTradingStatus("B"), "break");
assert.equal(moexTradingStatus("N"), "unavailable");
assert.equal(moexTradingStatus("F"), "closing");
for (const code of ["I", "S", "A", "a", "b", "p", "P"]) assert.equal(moexTradingStatus(code), "auction");
assert.equal(moexTradingStatus("?"), "unknown");
console.log("trading preparation contracts: ok");
