import assert from "node:assert/strict";
import { buildAiDataExport } from "../lib/ai-data/ai-data-export";
import type { ScreenerApiResponse } from "@screenerpro/shared";

const row = (ticker: string, change: number) => ({ ticker, shortName:ticker, assetClass:"stock" as const, lastPrice:100, previousClose:99, absoluteChange:1, percentChange:change, volume:1, turnover:200_000_000, open:99, high:102, low:98, tradesCount:10_000, stockActivityClass:"active" as const, tradingStatus:"open" as const, lotSize:1, updatedAt:"2026-07-21T10:00:00.000Z", sourceUpdatedAt:null, metrics:{turnoverRatio:null,volumeRatio:null,turnoverVsAverage:null,rangeVsAverage:null,tradesVsAverage:null,turnoverPercentile:null,tradesPercentile:null,rangePercentile:null,dayRangePct:4,gapPct:null,relativeVolatility20d:null,inPlayScore:90,isInPlay:true,inPlayTags:[],reasonLabel:null,currentTurnoverRub:200_000_000,previousDayTurnoverRub:null,activityRatio:null,requiredActivityRatio:null,sessionProgress:null,volumeRatioNow:2.4,tradesRatioNow:null,intradayBaselineStatus:"ok" as const,intradayBaselineKind:"intraday-ok" as const,baselineMode:"same-time" as const,baselineSource:"5d-average" as const,baselineTimeMsk:"10:00",baselineIsReliable:true,avgTurnoverAtTimeRub:null,avgTradesAtTimeRub:null,baselineSessionsCount:5,baselineWarning:null} });
const response = { assetClass:"stock", rows:[row("SBER",2),row("GAZP",-1)], benchmarks:[], status:{source:"moex",isDemo:false,degraded:false,baselineStatus:"ok",generatedAt:"2026-07-21T10:00:00.000Z",fetchTimestamp:"2026-07-21T10:00:00.000Z",sourceTimestamp:"2026-07-21T10:00:00.000Z",stockRows:2,futuresRows:0,fallbackReason:null,message:null}, diagnostics:undefined } as unknown as ScreenerApiResponse;
const result = buildAiDataExport(response,{mode:"market",universe:"all",depth:"compact",history:"current",shortlist:10,format:"ai-text",tickers:[]});
assert.equal(result.stocks.length,2); assert.ok(result.formats.aiText.includes("SBER|")); assert.equal(result.stocks.some((x) => Number.isNaN(x.rangePosition ?? 0)),false); assert.equal(result.stocks[0]?.return5m,null);
console.log("verify:ai-data-export OK");
