import {NextResponse} from "next/server";
import {fetchMoexFortsContractCandidates,resolveFuturesContractWithCandles} from "@/lib/server/services/futures-contract-resolver";
import type {FuturesContractBase} from "@/lib/domain/futures-contract-resolver";
import type {DataSpec,LiveDataResponse,LiveSession,LiveSessionPoint} from "@/lib/studio-v5/types";

function groupSessions(points:Array<{timestamp:string;close:number;volume?:number|null}>):LiveSession[]{const groups=new Map<string,Array<{timestamp:string;close:number;volume:number}>>();for(const p of points){const date=p.timestamp.slice(0,10),a=groups.get(date)||[];a.push({timestamp:p.timestamp,close:Number(p.close),volume:Number(p.volume||0)});groups.set(date,a)}return[...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,rows])=>{rows.sort((a,b)=>a.timestamp.localeCompare(b.timestamp));let cum=0;const start=rows[0]?new Date(rows[0].timestamp).getTime():0;const out:LiveSessionPoint[]=rows.map((p,i)=>{cum+=p.volume;const t=new Date(p.timestamp).getTime();return{timestamp:p.timestamp,price:p.close,volume:p.volume,cumVolume:cum,minute:Number.isFinite(t)&&start?Math.max(0,Math.round((t-start)/60000)):i}});return{date,totalVolume:cum,points:out}})}
function shiftDate(iso:string,days:number){const d=new Date(iso+"T12:00:00Z");d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function validTradingSession(s:LiveSession){const d=new Date(s.date+"T12:00:00Z"),day=d.getUTCDay();return day!==0&&day!==6&&s.points.length>=2&&s.totalVolume>0}
export async function GET(request:Request){
 const u=new URL(request.url),family=(u.searchParams.get("family")||"SI").toUpperCase() as FuturesContractBase,requestedSessions=Math.max(1,Math.min(5,Number(u.searchParams.get("sessions")||2))),interval=Math.max(1,Math.min(60,Number(u.searchParams.get("interval")||1))),fixedDate=u.searchParams.get("date")?.slice(0,10);
 if(!["SI","EU","CN"].includes(family))return NextResponse.json({ok:false,error:"Unsupported family"},{status:400});
 try{
  const candidates=await fetchMoexFortsContractCandidates();let resolved:any=null,sessions:LiveSession[]=[],resolution:"EXACT"|"NEAREST_PREVIOUS"|"RELATIVE"=fixedDate?"EXACT":"RELATIVE",exactError:string|null=null;
  if(fixedDate){
   try{resolved=await resolveFuturesContractWithCandles(family,candidates,{days:2,interval,dateRange:{from:fixedDate,till:fixedDate},historyMode:"sessions"});sessions=groupSessions((resolved.intraday?.points||[]).map((p:any)=>({timestamp:p.timestamp,close:p.close,volume:p.volume}))).filter(s=>s.date===fixedDate&&validTradingSession(s))}catch(e){exactError=e instanceof Error?e.message:String(e)}
   if(!sessions.length){const from=shiftDate(fixedDate,-16);resolved=await resolveFuturesContractWithCandles(family,candidates,{days:20,interval,dateRange:{from,till:fixedDate},historyMode:"sessions"});const available=groupSessions((resolved.intraday?.points||[]).map((p:any)=>({timestamp:p.timestamp,close:p.close,volume:p.volume}))).filter(s=>s.date<=fixedDate&&validTradingSession(s));if(!available.length)return NextResponse.json({ok:false,error:"NO_TRADING_SESSION_NEAR_DATE",requestedDate:fixedDate,details:exactError},{status:404,headers:{"Cache-Control":"no-store"}});sessions=[available.at(-1)!];resolution=sessions[0].date===fixedDate?"EXACT":"NEAREST_PREVIOUS"}
  }else{resolved=await resolveFuturesContractWithCandles(family,candidates,{days:12,interval,historyMode:"sessions"});sessions=groupSessions((resolved.intraday?.points||[]).map((p:any)=>({timestamp:p.timestamp,close:p.close,volume:p.volume}))).slice(-requestedSessions)}
  if(!sessions.length)return NextResponse.json({ok:false,error:"MOEX_ISS_NO_SESSIONS"},{status:502,headers:{"Cache-Control":"no-store"}});
  const resolvedDate=sessions.at(-1)?.date||null,asOf=sessions.at(-1)?.points.at(-1)?.timestamp||null;const spec:DataSpec={provider:"MOEX_ISS",instrument:{family,secid:resolved.contract.secid,resolver:"front_active_contract"},metric:"ohlcv_session",relativeRange:fixedDate?null:{tradingSessions:requestedSessions},fixedRange:fixedDate?{from:fixedDate,till:fixedDate}:null,transforms:["group_by_session","cumulative_volume"],display:{renderer:"studio_market_chart",crosshair:true,periodControl:true},updatePolicy:fixedDate?"AS_OF":"LIVE",asOf};
  const body:LiveDataResponse={ok:true,dataSpec:spec,instrument:{family,secid:resolved.contract.secid,expiryDate:resolved.contract.expiryDate,shortName:resolved.contract.shortName},sessions,source:{provider:"MOEX ISS",url:resolved.intraday?.debug?.candlesUrl,asOf,interval:resolved.intraday?.usedInterval||interval,diagnostics:[...(resolved.contract.diagnostics||[]),...(exactError?[`exact-date: ${exactError}`]:[])],requestedDate:fixedDate||null,resolvedDate,dateResolution:resolution}};
  return NextResponse.json(body,{headers:{"Cache-Control":fixedDate?"public, max-age=300":"public, max-age=30, stale-while-revalidate=60"}})
 }catch(error){const message=error instanceof Error?error.message:String(error);return NextResponse.json({ok:false,error:message},{status:502,headers:{"Cache-Control":"no-store"}})}
}
